services:
  web:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8888"
    
    

    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:
